### ISSUE TITLE
Spomladansko čiščenje

### ISSUE THREAD

**Issue by andrejbauer** [JerebP15/Abalone#7]
Da bomo lahko preživeli implementacijo minimax, bo treba najprej malo počistiti:

- [x] poskrbimo, da se povsod `oznaceni` preimenuje v `izbrani`
- [x] imamo podvajanje podatkov v igri: imamo spisek `self.izbrani`, hkrati pa vsako polje ve, ali je izbrano. Počistimo: v `Polje` ukinemo atribut `izbran` (oz. `oznacen`). GUI se bo znašel tako, da bo gledal v `self.igra.izbrani`
- [x] spremenimo `self.izbrani` tako, da bo spisek *koordinat* namesto spisek izbranih polj (vedno lahko dobimo pripadajoče polje preko `self.plosca`)
- [x] iz `Polje` pobrišemo kordinate
- [x] iz `Polje` pobrišemo `id`. GUI zdaj ne more več spravljati `id`-jev v `Polje` in `self.igra`, zato naj si naredi svojo tabelo (enake dimenzije), kjer hrani `id`-je.
- [x] v `Polje` je ostala samo barva. Ukinemo razred `Polje` in v `self.plosca` hranimo direktno barve
- [ ] to, kateri so izbrani, premaknemo v GUI. Se pravi, iz igre prestavimo `self.izbrani` v GUI. Pri raznih preverjanjih potez in premikih potez, mora GUI vedno podati potezo v obliki `(izbrani, p)` kjer so `izbrani` tisti, ki se premaknejo in `p` pove, kako premaknemo (zaenkrat je to še polje, na katerega smo kliknili, možno je, da bo nekoč to vektor premika)
- [ ] implementiraj metodo, ki vrne spisek možnih potez. Poteza je oblike `(izbrani, p)`, kot v prejšnji točki

**Comment by tjasabajc** [comment]
self.izbrani sva pustila v igri, sicer pa sva vse naredila, kot je zgoraj napisano.
